### ISSUE TITLE
Weird bug on windows phone

### ISSUE THREAD

**Issue by nk34player** [ramtinak/Minista#1]
Device Info:

Device : Lumia 640 XL LTE Dual SIM
Processor: ARM
Version : 2.0.60.0

Bug: Not able to access notification and also the profile page is always empty

(Note 1: Also i get the bug on my windows 10 laptop)
(Note 2: the image is cropped because of projecting program)

Pics: [Click Here](https://imgur.com/a/ZaB8UiT)

**Comment by ramtinak** [comment]
Hi, 
Thanks for letting me know,
I've fixed for the second part. and new release sent to MS Store (it'll be available within a few days)

About notification settings, It's not implemented yet. I just disable it for now. I will add it in future.

Regards.

**Comment by nk34player** [comment]
Thanks for the fix,

Do you have any idea when the notification thing will come back???

**Comment by ramtinak** [comment]
Bug fixed.
